apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service-2
  description: |
    A service for testing Backstage functionality. Configured for Circle CI
    and Rollbar.
  annotations:
    github.com/project-slug: RoadieHQ/sample-service-2
spec:
  type: library
  owner: User:dtuite
  lifecycle: incorrectvalue
  system: sample-system
  providesApis:
    - sample-service
  consumesApis:
    - spotify
  dependencyOf:
    - Component:sample-service-1
